#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01
# Configure ufw to block incoming traffic, except TCP ports: 22, 443, 80

apt-get intall ufw
sed -i 's/IPV6=.*/IPV=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default denyh incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
